# Generated by Django 3.2 on 2022-10-07 08:07

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('appointment_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(blank=True)),
                ('time_start', models.TimeField(blank=True)),
                ('time_end', models.TimeField(blank=True)),
                ('capacity', models.IntegerField(validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)])),
                ('vacancy', models.IntegerField(validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)])),
                ('description', models.CharField(max_length=10000, null=True)),
                ('location', models.CharField(max_length=1000, null=True)),
                ('topic', models.CharField(max_length=10000, null=True)),
                ('meeting_type', models.CharField(max_length=100, null=True)),
                ('status', models.CharField(max_length=100, null=True)),
                ('notes', models.CharField(max_length=10000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=10)),
                ('location', models.CharField(max_length=100)),
                ('building_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('unit_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=10000)),
                ('coordinator', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('tutor_id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, null=True)),
                ('units', models.ManyToManyField(to='backend.Unit')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, null=True)),
                ('faculty', models.CharField(max_length=100, null=True)),
                ('units', models.ManyToManyField(blank=True, to='backend.Unit')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('schedule_id', models.AutoField(primary_key=True, serialize=False)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='backend.appointment')),
                ('students', models.ManyToManyField(blank=True, to='backend.Student')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('bookind_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_time_booked', models.DateTimeField(null=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.appointment')),
                ('students', models.ManyToManyField(blank=True, to='backend.Student')),
                ('tutor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.tutor')),
            ],
        ),
        migrations.AddField(
            model_name='appointment',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.room'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='students',
            field=models.ManyToManyField(blank=True, to='backend.Student'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.tutor'),
        ),
    ]
