# Generated by Django 3.2 on 2022-10-12 01:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_appointment_vacancy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='vacancy',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)]),
        ),
    ]
