# Generated by Django 3.2 on 2022-10-24 13:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_alter_appointment_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='student_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='tutor',
            old_name='tutor_id',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateField(default=datetime.date(2022, 10, 24)),
        ),
    ]
