# Generated by Django 3.2 on 2022-10-28 08:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20221024_1331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='appointment',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='students',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='meeting_type',
            new_name='creator',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='appointment_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='topic',
            new_name='topics',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='date',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='description',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='room',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='status',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='time_end',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='time_start',
        ),
        migrations.AddField(
            model_name='appointment',
            name='duration',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(120)]),
        ),
        migrations.AddField(
            model_name='appointment',
            name='time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.DeleteModel(
            name='Schedule',
        ),
    ]
