# Generated by Django 3.2 on 2022-10-30 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_auto_20221028_0856'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='id',
            new_name='appointment_id',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='id',
            new_name='student_id',
        ),
        migrations.RenameField(
            model_name='tutor',
            old_name='id',
            new_name='tutor_id',
        ),
    ]
