# Generated by Django 3.2 on 2022-10-30 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_auto_20221030_1154'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='appointment_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='student_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='tutor',
            old_name='tutor_id',
            new_name='id',
        ),
    ]
