# Generated by Django 3.2 on 2022-11-03 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_auto_20221030_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='tutor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.tutor'),
        ),
    ]
